-- Début de la transaction : l'intéret c'est que si je fais 
--une erreur, c'est comme si rien n'était executé, 
--par contre si tout va bien c'est ok
BEGIN;
-- On supprime l'existant pour mieux recommencer
DROP TABLE IF EXISTS "rent";            -- En premier, car elle dépend de "user" et "car"
DROP TABLE IF EXISTS "car";             -- Ensuite, car elle dépend de "agency"
DROP TABLE IF EXISTS "user", "agency";  -- En dernier, ces tables peuvent être supprimées ensemble 
                                        --car elles ne dépendent pas d'autres tables dans cette commande
CREATE TABLE "user"(
"id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
"email" TEXT UNIQUE NOT NULL,
"password" TEXT NOT NULL,
"firstname" TEXT,
"lastname" TEXT 
);

CREATE TABLE "agency"(
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "email"  NOT NULL,
    "address" TEXT, 
    "phone_number" TEXT    
);

CREATE TABLE "car"(
    "id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "brand" TEXT, 
    "model" TEXT NOT NULL, 
    "power" SMALLINT, 
    "zero_to_100" SMALLINT,
    "max_speed" SMALLINT, 
    "eco_class" (VARCHAR), 
    "price" INTEGER,
    "agency_id" INTEGER REFERENCES "agency" ("id") NOT NULL
);

CREATE TABLE "rent"(
    "id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "date_start" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "date_end" TIMESTAMPTZ NOT NULL,
    "user_id" INTEGER REFERENCES "user" ("id") NOT NULL,
    "car_id" INTEGER REFERENCES "car" ("id") NOT NULL
);

-- fin de la transaction
COMMIT;
